name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Build the backend project with Maven
      - name: Build with Maven
        working-directory: vswapp-backend
        run: mvn clean install -B

      # Run tests
      - name: Run tests
        working-directory: vswapp-backend
        run: mvn test

      # Upload Surefire test reports
      - name: Upload Surefire Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: vswapp-backend/target/surefire-reports
