name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw
        working-directory: vswapp-backend

      - name: Build and run tests
        run: ./mvnw clean verify -Dspring.profiles.active=test
        working-directory: vswapp-backend

      - name: Archive test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: vswapp-backend/target/surefire-reports/
