name: VSwapp-CI

on:
push:
branches: [ main ]
pull_request:
branches: [ main ]

jobs:
build-and-test:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout repository
    uses: actions/checkout@v3
    with:
      fetch-depth: 0  # Needed for SonarQube analysis

  - name: Set up JDK 17
    uses: actions/setup-java@v3
    with:
      distribution: temurin
      java-version: 17

  - name: Cache Maven packages
    uses: actions/cache@v3
    with:
      path: ~/.m2/repository
      key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      restore-keys: |
        ${{ runner.os }}-maven-

  - name: Cache SonarQube packages
    uses: actions/cache@v3
    with:
      path: ~/.sonar/cache
      key: ${{ runner.os }}-sonar
      restore-keys: ${{ runner.os }}-sonar

  - name: Build project
    run: mvn clean install -DskipTests
    working-directory: vswapp-backend

  - name: Run only unit tests
    run: mvn test -Dtest=*ServiceTest,*RepositoryTest
    working-directory: vswapp-backend

  - name: Show test results
    run: cat target/surefire-reports/*.txt || true
    working-directory: vswapp-backend

  - name: Build and analyze with SonarQube
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Ishangi2002_Vswapp-QA
    working-directory: vswapp-backend
```
